version: "3.8"
services:
  server:
    container_name: pet-insurance-server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/app/
      - serverdata:/app/node_modules/
    ports:
      - "8080:80"
      - "5858:5858"
volumes:
  serverdata:
